server:
  port: 10000

spring:
  application:
    name: wuhan

  servlet:
    multipart:
      max-file-size: 10MB


  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxx.xxx.xxx.xxx:xxxx/xxxxx?characterEncoding=utf-8&useSSL=true
#    url: jdbc:mysql://localhost:3306/arms?characterEncoding=utf-8
    username: xxx
    password: xxx



  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      # spring boot 2.0 的坑， spring boot2.+后默认使用的是MyISAM引擎

    database: MySQL
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto: update

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML5



  freemarker:
    content-type: text/html
    #后缀名
    suffix: .ftl
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true

    #freemarker配置



#设置一个邮件发送人
lance:
  mail:
    sender: 381016296@qq.com

ScheduledTaskUrl:
  url: https://broccoli.uc.cn/apps/pneumonia/routes/index?uc_param_str=dsdnfrpfbivesscpgimibtbmnijblauputogpintnwktprchmt
